# Server Port Configuration
server.port=5000

# H2 File-Based Database Configuration (Restart చేసినా డేటా పోదు)
spring.datasource.url=jdbc:h2:file:./data/scamshielddb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false

# Spring Boot Frame Options Fix
spring.h2.console.settings.frame-options=sameorigin

# Permanent Gmail SSL Mail Configuration (Port 465 for Cloud / Render)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=nlavanya7866@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
